spring:
  application:
    name: media-service
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  config:
    import: optional:configserver:http://localhost:8881/
  cloud:
    config:
      uri: optional:configserver:http://localhost:8881/
      profile: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8055

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  root-dir: ${user.dir}

default:
  media:
    url:
      format: /media{0}
